export const MOTIVATIONAL_QUOTES = [
  "The only bad workout is the one that didn't happen.",
  "Your body can stand almost anything. It's your mind you have to convince.",
  "Success usually comes to those who are too busy to be looking for it.",
  "All progress takes place outside the comfort zone.",
  "If something stands between you and your success, move it. Never be denied.",
  "Well done is better than well said.",
  "No pain, no gain. Shut up and train.",
  "The hard days are the best because that's when champions are made.",
  "Don't limit your challenges. Challenge your limits.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "You miss 100% of the workouts you skip.",
  "Today I will do what others won't, so tomorrow I can accomplish what others can't.",
  "The groundwork for all happiness is good health.",
  "Take care of your body. It's the only place you have to live.",
  "Sweat is just fat crying.",
  "Push yourself because no one else is going to do it for you.",
  "When you feel like quitting, think about why you started.",
  "The body achieves what the mind believes.",
  "Don't stop when you're tired. Stop when you're done.",
  "Be stronger than your excuses.",
  "Your only limit is you.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Great things never come from comfort zones.",
  "It never gets easier, you just get stronger.",
  "Train insane or remain the same.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "One workout at a time. One day at a time. One meal at a time.",
  "You are one workout away from a good mood.",
  "Champions are not born. They are made in the gym.",
  "Your future self is watching you right now through your memories.",
  "The difference between try and triumph is a little umph.",
  "Results happen over time, not overnight. Work hard, stay consistent.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Someone busier than you is working out right now.",
  "Sore today. Strong tomorrow.",
  "What hurts today makes you stronger tomorrow.",
  "You don't have to be great to start, but you have to start to be great.",
  "First say to yourself what you would be, then do what you have to do.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Excuses don't burn calories.",
  "Success is what comes after you stop making excuses.",
  "Don't wish for it. Work for it.",
  "Discipline is choosing between what you want now and what you want most.",
  "Believe in yourself and all that you are.",
  "The secret of getting ahead is getting started.",
  "One pound at a time.",
  "Every rep counts. Make them all matter.",
  "Earn it.",
  "Be the change you wish to see in the gym.",
  "Progress, not perfection.",
]

export function getDailyQuote(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  )
  return MOTIVATIONAL_QUOTES[dayOfYear % MOTIVATIONAL_QUOTES.length]
}
